data <- read.table('household_power_consumption.txt',sep=';',header=F,skip=66637,nrows=2880)
dataColNames <- read.table('household_power_consumption.txt',sep=';',header=T,nrows=2)
colnames(data) <- colnames(dataColNames)
rm(dataColNames)
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data$Time <- paste(data$Date,data$Time)
data$Time <- strptime(data$Time, format = "%Y-%m-%d %H:%M:%S")
par(mar = c(4,4,2,2))
with(data, plot(Time, Global_active_power, type = 'l', ylab = "Global Active Power (kilowatts)", xlab = NA))
dev.copy(png,file = "plot2.png", width = 480, height = 480)
dev.off()