data <- read.table('household_power_consumption.txt',sep=';',header=F,skip=66637,nrows=2880)
dataColNames <- read.table('household_power_consumption.txt',sep=';',header=T,nrows=2)
colnames(data) <- colnames(dataColNames)
rm(dataColNames)
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data$Time <- paste(data$Date,data$Time)
data$Time <- strptime(data$Time, format = "%Y-%m-%d %H:%M:%S")
par(mfrow = c(1,1), mar = c(4,4,2,2))
with(data, plot(Time, Sub_metering_1, type = 'l', ylab = "Energy sub metering", xlab = NA))
with(data,lines(Time, Sub_metering_2, col="red"))
with(data,lines(Time, Sub_metering_3, col="blue"))
legend("topright",text.width = strwidth("Sub_metering_1"),cex=0.7,lwd = 1, lty = 1, col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file = "plot3.png", width = 480, height = 480)
dev.off()